/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Cristhian
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //ImageIcon imagen = new ImageIcon(getClass().getResource("/recursos/fondo_login.jpg"));
        //Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(label_fondo.getWidth(), label_fondo.getHeight(), Image.SCALE_DEFAULT));
        //label_fondo.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        label_user = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        chk_verificar = new javax.swing.JCheckBox();
        btn_acceder = new javax.swing.JButton();
        label_fondo = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_title.setText("Login");
        getContentPane().add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 24, -1, -1));

        label_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/user.png"))); // NOI18N
        getContentPane().add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 74, -1, -1));

        label_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/password.png"))); // NOI18N
        getContentPane().add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 128, -1, -1));

        txtuser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 87, 140, -1));

        txtpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 145, 140, -1));

        chk_verificar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chk_verificar.setText("Verificar");
        getContentPane().add(chk_verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 214, -1, -1));

        btn_acceder.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_acceder.setText("Acceder");
        btn_acceder.setEnabled(false);
        getContentPane().add(btn_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 214, -1, -1));
        getContentPane().add(label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -4, 310, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acceder;
    private javax.swing.JCheckBox chk_verificar;
    private javax.swing.JLabel label_fondo;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_user;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
    
    public void verificar(){
        String user="admin", password="admin01";
        if(user.equals(txtuser.getText()) && password.equals(txtpassword.getText())){
            btn_acceder.setEnabled(true);
        }else{
            
        }
    }
}
