/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Cristhian
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        login();
        menu.setVisible(false);
        new Thread(new hilo()).start();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        //escritorio.setBorder(new interfaces.ImagenFondo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        label_hora = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        m_modulos = new javax.swing.JMenu();
        sm_internet = new javax.swing.JMenuItem();
        m_tablas = new javax.swing.JMenu();
        m_movimientos = new javax.swing.JMenu();
        m_reportes = new javax.swing.JMenu();
        m_utilitarios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_hora.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        label_hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_hora.setText("Hora");

        escritorio.setLayer(label_hora, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(515, Short.MAX_VALUE)
                .addComponent(label_hora)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(label_hora)
                .addContainerGap())
        );

        m_modulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/modules.png"))); // NOI18N
        m_modulos.setText("Módulos");
        m_modulos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        sm_internet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sm_internet.setText("Internet");
        m_modulos.add(sm_internet);

        menu.add(m_modulos);

        m_tablas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tables.png"))); // NOI18N
        m_tablas.setText("Tablas");
        m_tablas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu.add(m_tablas);

        m_movimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/movements.png"))); // NOI18N
        m_movimientos.setText("Movimientos");
        m_movimientos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu.add(m_movimientos);

        m_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/reports.png"))); // NOI18N
        m_reportes.setText("Reportes");
        m_reportes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu.add(m_reportes);

        m_utilitarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/settings.png"))); // NOI18N
        m_utilitarios.setText("Utilitarios");
        m_utilitarios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu.add(m_utilitarios);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel label_hora;
    private javax.swing.JMenu m_modulos;
    private javax.swing.JMenu m_movimientos;
    private javax.swing.JMenu m_reportes;
    private javax.swing.JMenu m_tablas;
    private javax.swing.JMenu m_utilitarios;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem sm_internet;
    // End of variables declaration//GEN-END:variables

    public class hilo implements Runnable {

        @Override
        public void run() {
            new Timer(0, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Date d = new Date();
                    SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                    label_hora.setText(s.format(d));
                }
            }).start();

        }

    }
    
    public void login(){
        Login login=new Login();
        int x=(escritorio.getWidth())-login.getWidth()/2;
        int y=(escritorio.getHeight())-login.getHeight()/2;
        if(login.isShowing()){
            login.setLocation(x,y);
        }else{
            escritorio.add(login);
            login.setLocation(x,y);
            login.show();
        }       
    }
}
